version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
      - image: circleci/mysql
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: test
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: test
          POSTGRES_DB: test 
          POSTGRES_PASSWORD: test
      - image: circleci/redis
      - image: rabbitmq:3
      - image: circleci/cassandra:3.10
        environment:
          MAX_HEAP_SIZE: 2048m
          HEAP_NEWSIZE: 512m
    steps:
      - checkout
      - run: sudo pip install tox
      - run: tox -e py36
workflows:
  version: 2
  build:
    jobs:
      - build

